name: "Scheduled Cleanup GHCR Images" 

on: 
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag to delete'
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  cleanup:
    runs-on: ubuntu-dind
    steps:
      - name: Downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Delete GHCR Image
        run: |
          REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
                 
          IMAGES=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" | jq -r ' .[] | {tags: .metadata.container.tags, updated_at: .updated_at, id: .id} ')

          echo $IMAGES | while read -r IMAGE_INFO; do 
            TAGS=$(echo $IMAGE_INFO | jq -r '.tags')
            IMAGE_UPDATED_AT=$(echo $IMAGE_INFO | jq -r '.updated_at')
            IMAGE_ID=$(echo $IMAGE_INFO | jq -r '.id')
            DELETE_FLAG=true

            IMAGE_UPDATED_AT_EPOCH=$(date -d "${IMAGE_UPDATED_AT//Z/}" +"%s")

            CURRENT_EPOCH=$(date +"%s")

            SEVEN_DAYS_AGO=$((CURRENT_EPOCH - 7 * 24 * 60 * 60))

            if [[ $IMAGE_UPDATED_AT_EPOCH -ge $SEVEN_DAYS_AGO ]]; then
              IMAGE_UPDATED_AT_WITHIN_1_WEEK=true
            else
              IMAGE_UPDATED_AT_WITHIN_1_WEEK=false
            fi

            echo $TAGS | while read -r TAG; do
              if [[ "$TAG" == "latest" || "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$) || "$IMAGE_UPDATED_AT_WITHIN_1_WEEK" == "true" ]]; then
                DELETE_FLAG=false;
                break
              fi
            done

            if [ "$DELETE_FLAG" == "true" ]; then
              echo "Delete image with TAGS: $TAGS, UPDATED_AT: $IMAGE_UPDATED_AT, ID: $IMAGE_ID"
              curl -i -X DELETE -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$IMAGE_ID"
            fi
          done

      