name: "Scheduled Cleanup GHCR Images" 

on: 
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag to delete'
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  cleanup:
    runs-on: ubuntu-dind
    steps:
      - name: Downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Delete GHCR Image
        run: |
          REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
          
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  "https://ghcr.io/v2/${{ github.repository_owner }}/$REPO_NAME/tags/list" | jq .
          
          # VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" | jq -r '.[] | select(.metadata.container.tags[] == "${{ env.IMAGE_TAG }}") | .id')
          # echo "Package version ID: $VERSION_ID"
          # curl -i -X DELETE -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
      